updates

diff --git a/use-cases/automation/bigip/pipelines/bigip-pipeline.yml b/use-cases/automation/bigip/pipelines/bigip-pipeline.yml
--- a/use-cases/automation/bigip/pipelines/bigip-pipeline.yml
+++ b/use-cases/automation/bigip/pipelines/bigip-pipeline.yml
@@ -22,6 +22,7 @@ file_list_on_merge:
     paths:
       - file_added_merge.txt
       - file_deleted_merge.txt
+      
   only:
     - merge_requests
 
@@ -44,7 +45,7 @@ file_list_on_commit:
   only:
     - main
 
-validation:
+validation_on_merge:
   stage: validation
   tags:
     - shared  
@@ -53,7 +54,7 @@ validation:
   only:
     - merge_requests
   
-validation_on_commit:
+validation:
   stage: validation
   tags:
     - shared  
@@ -62,7 +63,7 @@ validation_on_commit:
   only:
     - main
 
-delete_from_bigip:
+Delete from BIGIP:
   stage: update
   allow_failure: true
   tags:
@@ -70,26 +71,28 @@ delete_from_bigip:
   script:
     - file_count=$(wc -l < files_deleted.txt)
     - echo "Number of declarations to be pushed on F5 are $file_count"
-    # Check if the file count is less than 1
     - |
-      if [ "$file_count" -lt 1 ]; then
-        echo "There are no declarations to be pushed. Exiting the pipeline."
-        exit 1
-      else
+      count=0  # check if any DELETE requests fail 
+      if [ "$file_count" -ge 1 ]; then
         # Read each line from the file and run a curl request
         while IFS= read -r data; do
           # Check if the line is not empty
           if [[ "$data" == */* ]]; then
-            echo "Running as3 post request for $data"
-            partition=$(echo "$data" | cut -d'/' -f1)
-            app_name=$(basename "$data" .json)
-            url='https://10.1.1.5/mgmt/shared/appsvcs/declare/'$partition'/applications/path-'$app_name
-            echo "Sending Delete for the following $url"
+            echo "Running as3 post request for $data"  # Just FYI
+            partition=$(echo "$data" | cut -d'/' -f1)  # extracting the partition name out of the filename
+            app_name=$(basename "$data" .json) # extracting the app name out of the filename
+            url='https://10.1.1.5/mgmt/shared/appsvcs/declare/'$partition'/applications/path-'$app_name # set the URL
+            echo "Sending DELETE request to the following $url"  # Just FYI
+            start_time=$(date +%s)  # Get the start time
             HTTP_CODE=$(curl -ks --output temp.json --write-out '%{http_code}' --header 'Authorization: Basic YWRtaW46SW5ncmVzc2xhYjEyMw==' --header 'Content-Type: application/json' --request DELETE $url)
+            end_time=$(date +%s) # Get the end time
+            elapsed_time=$((end_time - start_time)) # Calculate the elapsed time
+            echo "Time elapsed: $elapsed_time seconds" # Print the elapsed time
             if [[ ${HTTP_CODE} -ne 200 ]] ; then
               echo "ERROR - ${HTTP_CODE}"
               echo "Deletion for $data failed"
               cat temp.json
+              ((count++))
             else
               echo "Deletion for $data succeeded"
             fi
@@ -98,14 +101,20 @@ delete_from_bigip:
             echo "Excluding (top-level file) $data"
           fi
         done < "files_deleted.txt"
+      else
+        echo "There are no declarations to be pushed. Exiting the pipeline."
       fi
+
+      if [ "$count" -ge 1 ]; then
+        echo "Some AS3 Delete operations Failed. Please review the logs"
+        exit 1 # exit the pipeline
+      fi
+
   only:
     - main
 
 
-
-
-add_to_bigip:
+Add to BIGIP:
   stage: update
   allow_failure: true
   tags:
@@ -115,10 +124,8 @@ add_to_bigip:
     - echo "Number of declarations to be pushed on F5 are $file_count"
     # Check if the file count is less than 1
     - |
-      if [ $file_count -lt 1 ]; then
-        echo "There are no declarations to be pushed. Exiting the pipeline."
-        exit 1  # Exit the pipeline with a failure
-      else
+      count=0
+      if [ $file_count -ge 1 ]; then
         # Read each line from the file and run a curl request
         while IFS= read -r data; do
           # Check if the line is not empty
@@ -126,11 +133,17 @@ add_to_bigip:
             echo "Running as3 post request for $data"
             partition=$(echo "$data" | cut -d'/' -f1)
             url='https://10.1.1.5/mgmt/shared/appsvcs/declare/'$partition'/applications'
+            echo "Sending POST request to the following $url"  # Just FYI
+            start_time=$(date +%s)  # Get the start time
             HTTP_CODE=$(curl -ks --output temp.json --write-out '%{http_code}' --header 'Authorization: Basic YWRtaW46SW5ncmVzc2xhYjEyMw==' --header 'Content-Type: application/json' --data @$data --request POST $url)
+            end_time=$(date +%s) # Get the end time
+            elapsed_time=$((end_time - start_time)) # Calculate the elapsed time
+            echo "Time elapsed: $elapsed_time seconds" # Print the elapsed time
             if [[ ${HTTP_CODE} -ne 200 ]] ; then
               echo "ERROR - ${HTTP_CODE}"
               echo "Deployment for $data failed"
               cat temp.json
+              ((count++))
             else
               echo "Deployment for $data succeeded"
             fi
@@ -139,6 +152,14 @@ add_to_bigip:
             echo "Excluding (top-level file) $data"
           fi
         done < "files_added.txt"
+      else
+        echo "There are no declarations to be pushed. Exiting the pipeline."
       fi
+
+      if [ "$count" -ge 1 ]; then
+        echo "Some AS3 Delete operations Failed. Please review the logs"
+        exit 1 # exit the pipeline
+      fi
+
   only:
     - main
